char* imutToUpper(const char* std);
void mutToUpper(char* std);
char* imutToLower(const char* std);
void mutToLower(char* std);
char* imutFilterSp(const char* std);
void mutFilterSp(char* std);
char* imutFilter(const char* std);
void mutFilter(char* std);
char* imutDelSp(const char* std);
void mutDelSp(char* std);
